CREATE USER iwish IDENTIFIED BY iwish;

GRANT CREATE MATERIALIZED VIEW,
      CREATE PROCEDURE,
      CREATE SEQUENCE,
      CREATE SESSION,
      CREATE SYNONYM,
      CREATE TABLE,
      CREATE TRIGGER,
      CREATE TYPE,
      CREATE VIEW
  TO iwish;

ALTER USER iwish QUOTA UNLIMITED ON USERS;
